name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Fixed cron syntax
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with: # Fixed indentation and colon placement
          github_user_name: shreyashsri79
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
